[package]
name = "openssl-sys-extras"
version = "0.6.7"
authors = ["Steven Fackler <sfackler@gmail.com>"]
build = "build.rs"

[features]
ecdh_auto = []

[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.1"
openssl-sys = { version = "0.6.7", path = "../openssl-sys" }
